version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: flask_frontend
    volumes:
      - ./flask_frontend:/app
    ports:
      - "3000:3000"
    environment:
      - FLASK_ENV=development # development, production
    command: flask run --host=0.0.0.0 --port=3000 --reload
