services:
  backend:
    build:
      context: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:80"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - backend
    env_file:
      - .env
