version: '3.9'

services:
  # PostgreSQL Database Service
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: sololev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Mount the pgdata volume to persist data

  # Redis Service
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  # Web Application Service
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload # DEVELOPMENT ONLY
    # command: uvicorn app.main:app --host 0.0.0.0 --port 80 # PRODUCTION
    volumes:
      - .:/usr/src/app  # Mount the current directory to allow code changes
    ports:
      - "8000:80"
    depends_on:
      - db
      - redis

# Define named volumes
volumes:
  pgdata:
