{
 "title": "Main",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes / (16 * 1024 * 1024 * 1024) * 100",
     "legendFormat": "Virutal Memory"
    },
    {
     "expr": "process_resident_memory_bytes / (16 * 1024 * 1024 * 1024) * 100\n",
     "legendFormat": "Resident Memory"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100 / 4\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes / (16 * 1024 * 1024 * 1024) * 100",
     "legendFormat": "Virutal Memory"
    },
    {
     "expr": "process_resident_memory_bytes / (16 * 1024 * 1024 * 1024) * 100\n",
     "legendFormat": "Resident Memory"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100 / 4\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(http_requests_total) by (handler, method, status)\n",
     "legendFormat": "{{handler}} - {{method}} - {{status}}"
    }
   ]
  },
  {
   "title": "Request Duration (Latency)",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, handler))\n",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}