{
 "title": "Main",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes / 1024 / 1024 / 1024",
     "legendFormat": "RAM (GB)"
    },
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\"})\n",
     "legendFormat": "CPU Cores"
    }
   ]
  },
  {
   "title": "System Loads",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5s])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100)",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "System Loads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[10s])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100)",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Total Call Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Call Count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method, handler) (increase(http_requests_total[$__range]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Average Call Duration (ms)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_request_duration_seconds_sum[$__rate_interval])) / sum by (handler) (rate(http_request_duration_seconds_count[$__rate_interval])) * 1000\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{job=\"backend\"}",
     "maxLines": 100
    }
   ]
  }
 ]
}